"""
Package F -- ingest RAGloader/content/claims/*.md (generated by
build_claim_documents.py from data/claims/*.json) into Pinecone's 3-namespace
parent/child/proposition structure, using the shared RAGloader pipeline
(myAI6_RAG.py) -- same pipeline every other package's content goes through,
just repointed at the ~20-item ingredient knowledge base instead of myAI6's
original "owner" documents.

After each claim is upserted, this writes the resulting Pinecone PARENT
record id(s) back onto that claim's `vectorRefs` field in data/claims/*.json.
This is deliberate: retrieval at request time (lib/evidence.ts) fetches those
exact ids directly -- it is a metadata/id lookup, never an open semantic
search. See types/engine.ts's comment on Claim.vectorRefs and the
grade-laundering note in tasks/F-pinecone-evidence-ingestion.md.

evidenceTier metadata: every record this script creates (children, parents,
propositions) is also tagged evidenceTier="cited" -- the counterpart to
ingest_research_papers.py, which tags its broader, general-research corpus
evidenceTier="supplementary". Neither script's own retrieval changes because
of this tag (lib/evidence.ts still does its exact id lookup, unaffected); the
tag exists so a future semantic-search Q&A tool can filter to "cited" only by
default, and widen to "supplementary" only on request, so a real but
unrelated paper can never be mistaken for what actually justified a
recommendation.

Usage:
    cd RAGloader
    python build_claim_documents.py   # regenerate content/claims/*.md (safe, no creds)
    python ingest_claims.py           # ingest + write vectorRefs back (needs creds below)

    # Ingest one claim only (fast iteration while testing):
    python ingest_claims.py epa-dha-general-population-cv-prevention

Required env vars (not committed -- export them in your shell, or copy
env.template to .env.local and `source` it, before running):
    PINECONE_API_KEY     -- same key the app uses (see env.template)
    ANTHROPIC_API_KEY    -- same key the app uses; this pipeline's enrichment
                             and proposition-decomposition steps call the
                             Anthropic API directly
    UNSTRUCTURED_API_KEY -- required even for these markdown documents: the
                             pipeline parses every "research_paper"-type
                             document (any file type) through the Unstructured
                             platform API for structural parsing. Get a free
                             trial key at platform.unstructured.io.
Optional:
    PINECONE_INDEX_HOST  -- if unset, resolved automatically from
                             PINECONE_INDEX_NAME (config.ts's "myai6") via
                             the Pinecone control plane -- the index must
                             already exist (create it once in the Pinecone
                             console: name "myai6", integrated embedding
                             model llama-text-embed-v2).
    PINECONE_INDEX_NAME  -- defaults to "myai6" (must match config.ts's
                             PINECONE_INDEX_NAME).
"""
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
from myAI6_RAG import PipelineConfig, DocumentConfig, process_and_upsert, _rid, _collect_source_ids
from pinecone import Pinecone

REPO_ROOT = Path(__file__).resolve().parent.parent
CLAIMS_DIR = REPO_ROOT / "data" / "claims"
CONTENT_DIR = Path(__file__).resolve().parent / "content" / "claims"
EVIDENCE_TIER = "cited"


def load_pipeline_config() -> PipelineConfig:
    required = ("PINECONE_API_KEY", "ANTHROPIC_API_KEY", "UNSTRUCTURED_API_KEY")
    missing = [v for v in required if not os.environ.get(v)]
    if missing:
        raise SystemExit(
            f"Missing required env var(s): {', '.join(missing)}. "
            "See this file's docstring / env.template."
        )

    index_name = os.environ.get("PINECONE_INDEX_NAME", "myai6")
    index_host = os.environ.get("PINECONE_INDEX_HOST")
    if not index_host:
        pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"])
        try:
            index_host = pc.describe_index(index_name).host
        except Exception as e:
            raise SystemExit(
                f"Could not resolve host for Pinecone index '{index_name}': {e}\n"
                "Create the index in the Pinecone console first (integrated "
                "embedding model llama-text-embed-v2), or set PINECONE_INDEX_HOST directly."
            )

    return PipelineConfig(
        pinecone_api_key=os.environ["PINECONE_API_KEY"],
        pinecone_index_host=index_host,
        pinecone_index_name=index_name,
        anthropic_api_key=os.environ["ANTHROPIC_API_KEY"],
        unstructured_api_key=os.environ["UNSTRUCTURED_API_KEY"],
    )


def tag_evidence_tier(pcfg: PipelineConfig, source_name: str, tier: str = EVIDENCE_TIER):
    """Metadata-only patch (no re-embedding): sets evidenceTier on every
    record -- children, parents, propositions -- belonging to source_name."""
    index = Pinecone(api_key=pcfg.pinecone_api_key).Index(host=pcfg.pinecone_index_host)
    cfg = pcfg.cfg
    total = 0
    for ns in (cfg["pinecone_ns_children"], cfg["pinecone_ns_parents"], cfg["pinecone_ns_propositions"]):
        ids = _collect_source_ids(index, ns, source_name, deep=False)
        for vid in ids:
            index.update(id=vid, set_metadata={"evidenceTier": tier}, namespace=ns)
        total += len(ids)
    return total


def main():
    only = set(sys.argv[1:]) or None  # optional list of claim ids to limit to

    pcfg = load_pipeline_config()
    claim_files = sorted(CLAIMS_DIR.glob("*.json"))
    if not claim_files:
        raise SystemExit(f"No claim files found in {CLAIMS_DIR}")

    ingested, skipped, tagged = 0, 0, 0
    for claim_path in claim_files:
        claim = json.loads(claim_path.read_text())
        claim_id = claim["id"]
        if only and claim_id not in only:
            continue

        doc_path = CONTENT_DIR / f"{claim_id}.md"
        if not doc_path.exists():
            raise SystemExit(f"{doc_path} missing -- run build_claim_documents.py first.")

        first_citation_url = claim["citations"][0]["url"] if claim.get("citations") else ""
        doc_config = DocumentConfig(
            source_name=claim_id,
            source_description=f"Evidence claim: {claim_id}",
            source_url=first_citation_url,
            content_type="research_paper",
        )

        print(f"\n=== Ingesting {claim_id} ===")
        try:
            result = process_and_upsert(pcfg, str(doc_path), doc_config)
        except Exception as e:
            print(f"   FAILED: {e}")
            skipped += 1
            continue

        vector_refs = [_rid(claim_id, p.parent_id) for p in result.parent_chunks]
        claim["vectorRefs"] = vector_refs
        claim_path.write_text(json.dumps(claim, indent=2) + "\n")
        print(f"   vectorRefs -> {vector_refs}")

        n = tag_evidence_tier(pcfg, claim_id)
        print(f"   evidenceTier='{EVIDENCE_TIER}' set on {n} records")
        tagged += n
        ingested += 1

    print(f"\nDone. {ingested} ingested, {skipped} failed, {tagged} records tagged evidenceTier='{EVIDENCE_TIER}'.")
    print("Re-run build_claim_documents.py + this script whenever a claim's statement "
          "or citations change, so the index and vectorRefs stay in sync.")


if __name__ == "__main__":
    main()
